(add-to-list 'load-path "~/.emacs.d/init.d/")
(require 'init-meta)
(require 'init-backups)
(require 'init-interface)
(require 'init-evil)
(require 'init-helm)
(require 'init-completion)
(require 'init-check)
(require 'init-lisp)
(require 'init-parens)
(require 'init-web)
(require 'init-org)
(require 'init-python)
(require 'init-c)
