(add-to-list 'load-path "~/.emacs.d/init.d/")
(require 'init-meta)
(require 'init-backups)
(require 'init-interface)
(require 'init-evil)
(require 'init-helm)
(require 'init-check)
(require 'init-lisp)
(require 'init-parens)
(require 'init-web)
(require 'init-org)
(require 'init-python)
(require 'init-completion)
;; (require 'init-clojure)
;; (require 'init-evil)
;; (require 'init-helm)
;; (require 'init-python)
;; (require 'init-org)
;; (require 'init-completion)	 
;; (require 'init-ui)
;; (require 'init-web)
;; (setq line-number-display-limit-width 2000000) ;; prevents ?? for line numbers
;;(setq frame-resize-pixelwise t)
;; (when window-system (set-exec-path-from-shell-PATH))
